const state = { dataset: null, lineSeq: 0, lines: [], rfqId: null, snapshotId: null, runId: null, matches: null };
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const el = (tag, props = {}, children = []) => { const n = document.createElement(tag); Object.entries(props).forEach(([k,v]) => k === 'text' ? n.textContent = v : k === 'className' ? n.className = v : k === 'on' ? Object.entries(v).forEach(([e,f]) => n.addEventListener(e,f)) : n.setAttribute(k,v)); children.forEach(c => n.append(c)); return n; };
const fa = n => new Intl.NumberFormat('fa-IR').format(Number(n || 0));
const money = n => `${fa(n)} ریال`;
function applyTheme(theme){ document.documentElement.dataset.theme=theme; const button=$('#theme-toggle'); if(button){button.textContent=theme==='dark'?'☀':'☾';button.setAttribute('aria-label',theme==='dark'?'بازگشت به پوستهٔ روشن':'تغییر به پوستهٔ تیره');} }
function initTheme(){ const saved=localStorage.getItem('torob-theme'); const theme=saved||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'); applyTheme(theme); $('#theme-toggle')?.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('torob-theme',next);applyTheme(next);}); }
const api = async (path, options = {}) => { const r = await fetch(path, { headers: {'Content-Type':'application/json', ...(options.headers||{})}, ...options }); let body = null; try { body = await r.json(); } catch {} if (!r.ok) { const msg = body?.error?.message || body?.detail || body?.message || `خطای ${r.status}`; throw new Error(msg); } return body; };
function notice(text, type='info') { const n = $('#notice'); n.textContent = text; n.className = `notice ${type}`; n.hidden = !text; }
function lineDom(line) { const wrap = el('div', {className:'line', 'data-line-id':line.id}); const top = el('div',{className:'line-top'},[el('span',{className:'line-number',text:fa(state.lines.indexOf(line)+1)}), el('button',{type:'button',className:'remove-line',title:'حذف قلم',text:'×',on:{click:()=>removeLine(line.id)}})]); const query = el('div',{className:'field grow'}); query.append(el('label',{text:'نام کالا یا مشخصات'})); const input=el('input',{type:'text',className:'query-input',placeholder:'مثلاً خودکار آبی ۰.۷',value:line.query,autocomplete:'off'}); query.append(input); const suggestions=el('div',{className:'suggestions',role:'listbox'}); query.append(suggestions); input.addEventListener('input',()=>{ line.query=input.value; line.catalogItemId=null; updateRequestCount(); searchSuggestions(input,suggestions,line); }); const qty=el('div',{className:'field qty'}); qty.append(el('label',{text:'تعداد'})); const q=el('input',{type:'number',min:'1',step:'1',value:line.qty,'aria-label':'تعداد'}); q.addEventListener('input',()=>line.qty=q.value); qty.append(q); top.append(el('div',{className:'line-id',text:`قلم ${fa(state.lines.indexOf(line)+1)}`})); wrap.append(top,el('div',{className:'line-fields'},[query,qty])); return wrap; }
function renderLines(){ const root=$('#lines'); root.replaceChildren(...state.lines.map(lineDom)); updateRequestCount(); }
function addLine(query='', qty='1'){ const line={id:`line-${++state.lineSeq}`,query,qty}; state.lines.push(line); renderLines(); }
function removeLine(id){ if(state.lines.length<=2) return notice('درخواست باید حداقل دو قلم داشته باشد.','error'); state.lines=state.lines.filter(x=>x.id!==id); renderLines(); }
let searchTimer;
async function searchSuggestions(input, box, line){ clearTimeout(searchTimer); box.replaceChildren(); if(input.value.trim().length<2)return; searchTimer=setTimeout(async()=>{ try { const data=await api(`/api/catalog/search?q=${encodeURIComponent(input.value.trim())}${state.snapshotId?`&snapshot_id=${encodeURIComponent(state.snapshotId)}`:''}`); const candidates=data.candidates||[]; if(!candidates.length){box.append(el('div',{className:'suggestion-empty',text:'نامزدی پیدا نشد'}));return;} candidates.slice(0,6).forEach(item=>{ const b=el('button',{type:'button',className:'suggestion',role:'option'}); b.append(el('b',{text:item.title||item.name||item.catalog_item_id||'کالای بدون نام'}),el('small',{text:`${item.unit||item.base_unit||''} · ${fa(item.offer_count)} پیشنهاد`})); b.addEventListener('click',()=>{line.query=item.title||item.name||input.value; line.catalogItemId=item.catalog_item_id||item.id; input.value=line.query; box.replaceChildren();}); box.append(b); }); } catch(e){ /* search is progressive; submit still reports validation */ } },260); }
function readForm(){ const budget=$('#budget').value.replace(/[^0-9۰-۹]/g,'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)); return {lines:state.lines.map(l=>({id:l.id,query_text:l.query,qty_base:Number(l.qty),catalog_item_id:l.catalogItemId||null})), budget_irr:budget?Number(budget):null,max_lead_days:$('#lead').value?Number($('#lead').value):null,requires_declared_invoice:$('#invoice').checked,preference:$('input[name=preference]:checked').value}; }
async function submitRFQ(e){e.preventDefault(); notice('در حال ثبت درخواست و تطبیق اقلام…'); const payload=readForm(); if(payload.lines.some(l=>!l.query_text.trim()||!Number.isInteger(l.qty_base)||l.qty_base<1)){notice('نام کالا و تعداد معتبر برای همهٔ اقلام لازم است.','error');return;} try { const data=await api('/api/rfqs',{method:'POST',body:JSON.stringify({snapshot_id:state.snapshotId,...payload})}); state.rfqId=data.rfq_id; state.snapshotId=data.snapshot_id||state.snapshotId; state.matches=data.matches||null; $('#form-view').hidden=true; $('#match-view').hidden=false; renderMatches(data.matches||[]); notice(''); window.scrollTo({top:0,behavior:'smooth'}); } catch(e){notice(e.message,'error');} }
function renderMatches(matches){ const root=$('#matches'); root.replaceChildren(); const catalog=new Map((state.dataset?.catalog||[]).map(x=>[x.id,x])); (matches||[]).forEach(m=>{ const line=state.lines.find(x=>x.id===m.line_id); const box=el('article',{className:`match-item ${m.status}`}); const head=el('div',{className:'match-head'},[el('div',{className:'match-name',text:line?.query||m.line_id}),el('span',{className:`status status-${m.status}`,text:m.status==='confirmed'?'تأییدشده':m.status==='ambiguous'?'نیازمند انتخاب':'بدون تطبیق'})]); box.append(head); if(m.method)box.append(el('p',{className:'match-reason',text:m.status==='ambiguous'?'چند نامزد سازگار پیدا شد؛ یکی را انتخاب کن.':m.status==='unmatched'?'برای این عبارت کالای سازگار در snapshot پیدا نشد.':`تطبیق با روش ${m.method} ثبت شد.`})); const candidates=m.candidate_catalog_ids||[]; if(m.status!=='confirmed'&&candidates.length){ const list=el('div',{className:'candidate-list'}); candidates.forEach(id=>{const c=catalog.get(id)||{id}; const label=el('label',{className:'candidate'}); const radio=el('input',{type:'radio',name:`match-${m.line_id}`,value:id}); radio.addEventListener('change',()=>m.selected=id); label.append(radio,el('span',{},[el('b',{text:c.name||id}),el('small',{text:`${c.base_unit||''} · کالای ${c.category||'کاتالوگ'}`} )])); list.append(label);}); box.append(list); } else if(m.selected_catalog_id) box.append(el('p',{className:'confirmed-sku',text:`SKU: ${m.selected_catalog_id}`})); root.append(box); }); }
async function runEvaluation(preference, showResults=true){ try { notice('در حال بررسی همهٔ ترکیب‌های ممکن…'); const started=await api(`/api/rfqs/${state.rfqId}/evaluate`,{method:'POST',body:JSON.stringify({snapshot_id:state.snapshotId,preference})}); state.runId=started.run_id; const result=await api(`/api/runs/${state.runId}`); renderResults(result); if(showResults){$('#match-view').hidden=true;$('#results-view').hidden=false;window.scrollTo({top:0,behavior:'smooth'});} notice(''); }catch(e){notice(e.message,'error');} }
async function evaluate(){ const unresolved=(state.matches||[]).filter(m=>m.status!=='confirmed'&&!m.selected); if(unresolved.length){notice('برای ادامه، برای هر قلم مبهم یک SKU انتخاب کن.','error');return;} try { for(const m of state.matches||[]){if(m.selected) { const updated=await api(`/api/rfqs/${state.rfqId}/matches/${m.line_id}`,{method:'PUT',body:JSON.stringify({catalog_item_id:m.selected})}); m.status='confirmed'; m.selected_catalog_id=m.selected; if(updated.matches) state.matches=updated.matches; }} await runEvaluation($('input[name="preference"]:checked').value); }catch(e){notice(e.message,'error');} }
function renderResults(result){ const combos=result.combinations||[]; const statusLabel=result.status==='ok'?'قابل بررسی':result.status==='no_full_coverage'?'پوشش کامل پیدا نشد':result.status==='search_limit'?'سقف جست‌وجو رد شد':'اجرای ناموفق'; $('#results-subtitle').textContent=`${result.search_exhaustive?'جست‌وجوی کامل':'جست‌وجوی محدود'} · ${fa(result.enumerated_combinations)} ترکیب بررسی شد · اولویت: ${result.preference==='fastest_delivery'?'سریع‌ترین تحویل':'کمترین هزینه'}`; $('#result-summary').replaceChildren(el('div',{className:'summary-chip'},[el('span',{text:'snapshot'}),el('b',{text:result.snapshot_id||state.snapshotId||'—'})]),el('div',{className:'summary-chip'},[el('span',{text:'وضعیت'}),el('b',{text:statusLabel})]),el('div',{className:'summary-chip'},[el('span',{text:'منبع'}),el('b',{text:'پیشنهادهای ثبت‌شده'})])); const root=$('#results'); root.replaceChildren(); combos.slice(0,8).forEach((c,i)=>root.append(comboCard(c,i,result.preference))); const uncovered=result.uncovered_lines||[]; const excluded=result.excluded_reasons||[]; $('#uncovered').hidden=!uncovered.length&&!excluded.length; if(!$('#uncovered').hidden){const box=$('#uncovered');box.replaceChildren(el('h3',{text:result.status==='search_limit'?'جست‌وجو به سقف مجاز رسید':'اقلام یا ترکیب‌های کنارگذاشته‌شده'})); uncovered.forEach(u=>box.append(el('p',{text:`${(u.line_ids||[]).join('، ')}: ${(u.reason_codes||[]).join('، ')}`}))); if(result.status==='search_limit')box.append(el('p',{text:'برای این درخواست هیچ رتبه‌ای تا کامل‌شدن جست‌وجو نمایش داده نمی‌شود.'}));} }
function comboCard(c,i,pref){ const card=el('article',{className:`combo-card ${i===0?'top':''}`}); const catalog=new Map((state.dataset?.catalog||[]).map(x=>[x.id,x])); const vendors=new Map((state.dataset?.vendors||[]).map(x=>[x.id,x])); const badge=i===0?el('span',{className:'best-badge',text:'پیشنهاد اول بر اساس ترجیح شما'}):el('span',{className:'rank',text:`رتبه ${fa(c.rank||i+1)}`}); const head=el('div',{className:'combo-head'},[badge,el('div',{className:'combo-total'},[el('small',{text:'جمع کل'}),el('strong',{text:money(c.total_irr)}),el('span',{text:`تحویل تا ${fa(c.max_lead_days)} روز`})])]); card.append(head); const reason=c.reason||c.reason_data||{}; let reasonText=reason.criterion==='max_lead_days'?`به‌دلیل زمان تحویل ${fa(c.max_lead_days)} روز انتخاب شده است.`:`به‌دلیل جمع کل ${money(c.total_irr)} در اولویت هزینه قرار گرفته است.`; if(reason.difference)reasonText+=` اختلاف با گزینهٔ مقایسه ${fa(reason.difference)} ${reason.difference_unit==='days'?'روز':'ریال'} است.`; card.append(el('p',{className:'reason',text:reasonText})); const table=el('div',{className:'assignment-table'}); table.append(el('div',{className:'table-row table-header'},[el('span',{text:'قلم'}),el('span',{text:'فروشنده'}),el('span',{text:'تعداد / اضافه'}),el('span',{text:'هزینه'})])); const invoiceStates=[]; (c.assignments||[]).forEach(a=>{const vendor=vendors.get(a.vendor_id); const item=catalog.get(a.catalog_item_id); if(a.invoice_status) invoiceStates.push(a.invoice_status); const row=el('div',{className:'table-row'},[el('span',{text:item?.name||a.catalog_item_id||a.line_ids?.join('، ')||'—'}),el('span',{text:vendor?.name||a.vendor_id||'—'}),el('span',{text:`${fa(a.covered_qty_base)} عدد / ${fa(a.overbuy_qty_base)} اضافه`}),el('span',{text:money(a.line_total_irr)})]); const offer=el('button',{type:'button',className:'provenance-link',text:'مشاهدهٔ منشأ'}); offer.addEventListener('click',()=>openProvenance(a.offer_id)); row.lastChild.append(offer); table.append(row);}); card.append(table); const invoiceLabel=invoiceStates.length&&invoiceStates.every(x=>x==='declared_yes'||x==='verified_yes')?'فاکتور: طبق اظهار فروشنده':invoiceStates.some(x=>x==='declared_no')?'فاکتور: برای برخی اقلام اعلام نشده':'فاکتور: وضعیت در داده ثبت نشده'; const foot=el('div',{className:'combo-foot'},[el('span',{text:`ارسال: ${money(c.shipping_total_irr)}`}),el('span',{text:`${fa(c.vendor_count)} فروشنده`}),el('span',{text:invoiceLabel})]); card.append(foot); return card; }
async function openProvenance(id){try{const d=await api(`/api/offers/${encodeURIComponent(id)}/provenance`);const root=$('#provenance-content');root.replaceChildren(); const fields=[['پیشنهاد',d.offer?.id||id],['فروشنده',d.vendor?.name||d.vendor?.id],['کالا',d.catalog_item?.title||d.catalog_item?.name||d.catalog_item?.id],['منبع',d.source_label||d.raw?.source_label],['رکورد خام',d.raw?.raw_title||d.raw?.id],['قیمت خام',d.raw?.raw_price_text],['واحد خام',d.raw?.raw_unit_text],['ثبت داده',d.raw?.generated_at||d.raw?.observed_at]]; fields.filter(([,v])=>v!=null).forEach(([k,v])=>root.append(el('div',{className:'provenance-row'},[el('span',{text:k}),el('b',{text:String(v)})]))); if(d.offer?.normalization_steps)root.append(el('p',{className:'normalization',text:`تبدیل‌های ثبت‌شده: ${d.offer.normalization_steps.join('، ')}`})); $('#provenance-dialog').showModal();}catch(e){notice(e.message,'error');}}
async function loadDataset(){try{const d=await api('/api/datasets/active');state.dataset=d;const meta=d.metadata||{};state.snapshotId=meta.id||d.snapshot_id||d.id;const label=`${meta.id||'demo-v1'} · ${meta.captured_at||'۱۴۰۵/۰۶/۲۵'}`;$('#snapshot-label').textContent=label;$('#footer-snapshot').textContent=label;$('#dataset-name').textContent=meta.version||meta.id||'snapshot فعال';$('#dataset-meta').textContent=`${fa(d.counts?.catalog_items)} کالا · ${fa(d.counts?.vendors)} فروشنده`; }catch(e){$('#snapshot-label').textContent='snapshot محلی · دمو';$('#dataset-name').textContent='دموی محلی';$('#dataset-meta').textContent='برچسب داده در API در دسترس نیست';}}
document.addEventListener('DOMContentLoaded',()=>{addLine();addLine();loadDataset();$('#add-line').addEventListener('click',()=>addLine());$('#rfq-form').addEventListener('submit',submitRFQ);$('#evaluate').addEventListener('click',evaluate);const backToForm=()=>{$('#match-view').hidden=true;$('#results-view').hidden=true;$('#form-view').hidden=false;notice('');window.scrollTo({top:0,behavior:'smooth'});};$('#edit-from-match').addEventListener('click',backToForm);$('#edit-request').addEventListener('click',backToForm);$('#close-dialog').addEventListener('click',()=>$('#provenance-dialog').close());$$('input[name=preference]').forEach(r=>r.addEventListener('change',()=>$$('.radio-card').forEach(x=>x.classList.toggle('active',x.querySelector('input').checked))));$$('.intent-button').forEach(button=>button.addEventListener('click',async()=>{const preference=button.dataset.preference;$$('.intent-button').forEach(x=>x.classList.toggle('active',x===button));await runEvaluation(preference,false);}));});
const _renderResults = renderResults;
renderResults = function(result) {
  _renderResults(result);
  if ((result.combinations || []).length || !(result.excluded_reasons || []).length) return;
  const box = $('#uncovered');
  const labels = {EXCEEDS_BUDGET:'از سقف بودجه عبور می‌کند', EXCEEDS_MAX_LEAD_DAYS:'از حداکثر زمان تحویل عبور می‌کند', BELOW_VENDOR_MINIMUM_ORDER:'به حداقل خرید فروشنده نمی‌رسد', INVOICE_NOT_DECLARED:'فاکتور اعلام‌شده ندارد', INSUFFICIENT_STOCK:'موجودی کافی ندارد', UNKNOWN_SHIPPING:'هزینهٔ ارسال نامشخص است'};
  const basketCodes = new Set(['EXCEEDS_BUDGET','EXCEEDS_MAX_LEAD_DAYS','BELOW_VENDOR_MINIMUM_ORDER','INVOICE_NOT_DECLARED','SEARCH_LIMIT']);
  const codes = [...new Set((result.excluded_reasons || []).filter(x => !x.catalog_item_id && (x.offer_ids || x.reason_codes?.some(c => basketCodes.has(c)))).flatMap(x => x.reason_codes || []).filter(c => basketCodes.has(c)))];
  if (!codes.length) return;
  box.append(el('p',{className:'excluded-summary',text:`هیچ سبد کاملی با این محدودیت‌ها واجد شرایط نشد: ${codes.map(c=>labels[c]).join('، ')}.`}));
  box.append(el('button',{type:'button',className:'button button-ghost empty-edit',text:'ویرایش بودجه یا محدودیت‌ها',on:{click:()=>{$('#results-view').hidden=true;$('#form-view').hidden=false;window.scrollTo({top:0,behavior:'smooth'});}}}));
};
document.addEventListener('DOMContentLoaded',initTheme);

// The catalog is the entry point; RFQ remains the second step of the demo.
const shop = {items:[], category:'all', query:''};
const normalizeSearch = value => String(value || '').toLocaleLowerCase('fa-IR').replace(/ي/g,'ی').replace(/ك/g,'ک').trim();
function updateRequestCount(){const target=$('#request-count');if(target)target.textContent=fa(state.lines.filter(line=>line.query.trim()).length);}
function showMainView(name){
  ['storefront','workflow','business'].forEach(view=>{$(`#${view}-view`).hidden=view!==name;});
  $$('.nav-link').forEach(button=>{const active=button.dataset.view===name;button.classList.toggle('active',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});
  if(name==='workflow'){$('#form-view').hidden=false;$('#match-view').hidden=true;$('#results-view').hidden=true;notice('');}
  window.scrollTo({top:0,behavior:'smooth'});
}
function addCatalogItemToRequest(item, qty=1){
  let line=state.lines.find(entry=>!entry.query.trim());
  if(!line){line={id:`line-${++state.lineSeq}`,query:'',qty:'1'};state.lines.push(line);}
  line.query=item.name;line.qty=String(qty);line.catalogItemId=item.id;
  renderLines();if($('#product-dialog').open)$('#product-dialog').close();showMainView('workflow');
  const count=state.lines.filter(entry=>entry.query.trim()).length;
  notice(count<2?`${item.name} به فهرست خرید اضافه شد. برای مقایسه، دست‌کم یک قلم دیگر هم وارد کنید.`:`${item.name} به فهرست خرید اضافه شد. تعداد و شرایط را بررسی کنید.`);
}
function productVisual(item){const name=item.name||'';if(item.id?.startsWith('paper'))return 'A4';if(item.id?.startsWith('mouse'))return '⌁';return name.includes('۰.۷')||name.includes('0.7')?'۰٫۷':'✎';}
function cardPrice(item){const price=item.lowest_package_price_irr??item.min_package_price_irr??item.lowest_offer_price_irr;return price==null?'قیمت ثبت نشده':money(price);}
function renderCategoryFilters(){
  const root=$('#category-filters');const categories=['all',...new Set(shop.items.map(item=>item.category).filter(Boolean))];
  root.replaceChildren(...categories.map(category=>{const button=el('button',{type:'button',className:`filter-chip ${shop.category===category?'active':''}`,text:category==='all'?'همهٔ کالاها':category});button.setAttribute('aria-pressed',String(shop.category===category));button.addEventListener('click',()=>{shop.category=category;renderCategoryFilters();renderCatalog();});return button;}));
}
function renderCatalog(){
  const q=normalizeSearch(shop.query);const items=shop.items.filter(item=>(shop.category==='all'||item.category===shop.category)&&(!q||normalizeSearch(`${item.name} ${item.id} ${(item.aliases||[]).join(' ')}`).includes(q)));
  $('#catalog-total').textContent=`${fa(items.length)} کالا`;
  $('#catalog-empty').hidden=items.length>0;
  const grid=$('#product-grid');grid.replaceChildren();
  items.forEach(item=>{
    const card=el('article',{className:'product-card'});
    card.append(el('div',{className:`product-visual ${item.category==='تجهیزات IT'?'product-visual-it':''}`,text:productVisual(item)}));
    const info=el('div',{className:'product-info'},[el('span',{className:'product-category',text:item.category||'کالا'}),el('h3',{text:item.name}),el('p',{text:`${fa(item.offer_count??item.accepted_offer_count??0)} پیشنهاد پذیرفته‌شده · واحد: ${item.base_unit||'عدد'}`})]);
    const price=el('div',{className:'product-price'},[el('small',{text:'کمترین قیمت بسته'}),el('strong',{text:cardPrice(item)})]);
    const actions=el('div',{className:'product-actions'});
    actions.append(el('button',{type:'button',className:'button button-ghost',text:'جزئیات پیشنهادها',on:{click:()=>openProduct(item.id)}}),el('button',{type:'button',className:'button button-primary',text:'افزودن به فهرست',on:{click:()=>addCatalogItemToRequest(item)}}));
    card.append(info,price,actions);grid.append(card);
  });
}
async function loadCatalog(){
  try{const data=await api('/api/catalog/items');shop.items=(data.items||[]).map(item=>({...item,id:item.catalog_item_id||item.id,offer_count:item.accepted_offer_count}));renderCategoryFilters();renderCatalog();$('#catalog-error').hidden=true;}
  catch(error){$('#product-grid').replaceChildren();const box=$('#catalog-error');box.textContent=`کاتالوگ بارگذاری نشد: ${error.message}`;box.hidden=false;$('#catalog-total').textContent='—';}
}
async function openProduct(id){
  const dialog=$('#product-dialog');const content=$('#product-dialog-content');content.replaceChildren(el('p',{className:'catalog-loading',text:'در حال خواندن پیشنهادها…'}));dialog.showModal();
  try{
    const data=await api(`/api/catalog/items/${encodeURIComponent(id)}`);const item=data.item||shop.items.find(x=>x.id===id)||{};const offers=data.offers||[];
    $('#product-dialog-title').textContent=item.name||'جزئیات کالا';content.replaceChildren();
    content.append(el('p',{className:'product-dialog-intro',text:`${item.category||'کالا'} · ${fa(offers.length)} پیشنهاد پذیرفته‌شده · snapshot فعال`}));
    if(!offers.length)content.append(el('p',{className:'catalog-loading',text:'پیشنهاد پذیرفته‌شده‌ای برای این کالا ثبت نشده است.'}));
    offers.forEach(offer=>{
      const row=el('article',{className:'offer-row'});const vendor=offer.vendor_name||offer.vendor?.name||offer.vendor_id||'فروشندهٔ نمونه';
      row.append(el('div',{className:'offer-row-title'},[el('b',{text:vendor}),el('strong',{text:money(offer.package_price_irr)})]));
      row.append(el('p',{text:`بستهٔ ${fa(offer.package_size_base)} ${item.base_unit||'عدد'} · تحویل ${fa(offer.lead_days)} روز · موجودی ${fa(offer.stock_packages)} بسته` }));
      row.append(el('small',{text:offer.invoice_status==='declared_yes'?'فاکتور: طبق اظهار فروشنده':'فاکتور: اعلام‌نشده یا نامشخص'}));
      const source=el('button',{type:'button',className:'provenance-link',text:'مشاهدهٔ منشأ'});source.addEventListener('click',()=>{dialog.close();openProvenance(offer.offer_id||offer.id);});row.append(source);content.append(row);
    });
    const action=el('div',{className:'product-dialog-action'});const label=el('label',{text:'تعداد موردنیاز'});const qty=el('input',{type:'number',min:'1',step:'1',value:'1','aria-label':'تعداد موردنیاز'});const add=el('button',{type:'button',className:'button button-primary',text:'افزودن به فهرست خرید'});add.addEventListener('click',()=>{const count=Number(qty.value);if(!Number.isInteger(count)||count<1){qty.setCustomValidity('تعداد باید عدد صحیح مثبت باشد');qty.reportValidity();return;}addCatalogItemToRequest(item,count);});action.append(label,qty,add);content.append(action);
  }catch(error){content.replaceChildren(el('p',{className:'notice error',text:`جزئیات کالا بارگذاری نشد: ${error.message}`}));}
}
document.addEventListener('DOMContentLoaded',()=>{
  $$('[data-view]').forEach(button=>button.addEventListener('click',()=>showMainView(button.dataset.view)));
  $('#brand-home').addEventListener('click',event=>{event.preventDefault();showMainView('business');});
  $('#catalog-query').addEventListener('input',event=>{shop.query=event.target.value;renderCatalog();});
  $('#clear-catalog-search').addEventListener('click',()=>{$('#catalog-query').value='';shop.query='';shop.category='all';renderCategoryFilters();renderCatalog();$('#catalog-query').focus();});
  $('#start-demo').addEventListener('click',()=>{state.lines=[];state.lineSeq=0;addLine('خودکار آبی 0.7','13');addLine('ماوس USB مدل M100','2');showMainView('workflow');});
  $('#business-start').addEventListener('click',()=>showMainView('workflow'));
  $('#close-product-dialog').addEventListener('click',()=>$('#product-dialog').close());
  $('#product-dialog').addEventListener('click',event=>{if(event.target.id==='product-dialog')event.target.close();});
  loadCatalog();
});
